### ISSUE TITLE
Add a radius to the Recent Activity feed

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#292]
User feedback:
- Ability to expand range of activity feed.

Similar to how you can change the radius to the Events feed.

This makes sense in areas like Japan, but less sense in areas like Southern California. Thoughts?

This is the last open item from the [5.0.0 feedback](https://github.com/bpoore/pbm-react/issues/234) issue.

**Comment by bpoore** [comment]
From the app, we don't have an ability currently to allow the user to expand the radius due to a maximum being imposed by the API of 30 miles https://github.com/scottwainstock/pbm/blob/2106c90f6d8be428830ea63efbd4eb6b506ed7bb/app/controllers/api/v1/user_submissions_controller.rb#L20.

We could easily make the radius selectable as it is in the events feed if the API would support such behavior. Personally, I'm not sure how people are using this feature... the 30 mile radius is being applied to the lat/lon of the current map extant. If it would enhance some people's experience to be able to select a different radius value, that seems cool. I don't really use this feature in a way where I find myself wishing this was available personally.

**Comment by RyanTG** [comment]
The users that have requested this live in places like Japan and Finland, where stuff is sparse and far apart!

I'm not _super_ into this idea, but they keep requesting it! So yeah, we should start with a pbm issue to... add an endpoint for this value, instead of baking it in.

**Comment by bpoore** [comment]
We could potentially not show the options for a larger radius if there are greater than X entries in the list for the current map extant. That way the feature would only be available in sparse areas.

**Comment by RyanTG** [comment]
I just looked into this and this doesn't actually need API work! 

It's true that we have `MAX_MILES_TO_SEARCH_FOR_USER_SUBMISSIONS` in the API controller. However, that is a _default_ and can be overwritten using the `max_distance` param. 

Example:
https://pinballmap.com/api/v1/user_submissions/list_within_range.json?lat=34.11959605969743;lon=-118.21801350171755;max_distance=50

**Comment by RyanTG** [comment]
For the record: I took one stab at this, then Beth did it better. Branch here. https://github.com/pinballmap/pbm-react/tree/recent-activity

Currently merged into master and will be included in 5.2.18 release.

**Comment by RyanTG** [comment]
Really annoying how github doesn't show exact dates for all commits. "two weeks ago" "last month" etc. Anyway, I added the new submission fields on Mon Jan 23, 2023 - which means that by the time our next app release is out, it will be 30 days and so we can potentially use the new fields for this radius. So I'll think about how we can do that, and will comment here with it.

**Comment by RyanTG** [comment]
New user_submission fields:

  > "comment",
  > "user_name",
  > "location_name",
  > "machine_name",
  > "high_score"


**submission_types:**

**NEW_LMX**

`${machine_name} added to ${location_name}
- ${user_name}, ${created_at}`


**NEW_CONDITION**

`"${comment}" 
- ${user_name}, ${created_at}`


**REMOVE_MACHINE**

`${machine_name} removed from  ${location_name}
- ${user_name}, ${created_at}`


**NEW_SCORE**

`${high_score} on ${machine_name} at ${location_name}
- ${user_name}, ${created_at}`


**CONFIRM_LOCATION**

`${user_name} confirmed the line-up at ${location_name}
- ${created_at}`
