### ISSUE TITLE
How to speed up huge locations

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#360]
There are a couple outlier locations with a ton of machines (Next Level, Museum of Pinball, etc). Not only do those locations take a while to load, they sometimes cause the server to timeout.

Additionally Expo has noted that they are huge lists and they suggest using lazy loading or something (I’m usually in the middle of something else when I see the warning).

I do not know the solution, nor do I know if the solution will involve an API update. But it would be great to slim down these huge locations. I think they even slow down the map, too.

One wild idea is to disable machine comments for places with over x machines. If we could totally exclude comments, I’d think it would speed things up? Not sure how to do that, though.

Any other ideas?

**Comment by bpoore** [comment]
I believe we have potentially a few separate areas of concern here. When the map is pulled up, the data the app has in the redux store is coming from our request for getting locations. There's an array of machine_names and machine_ids coming back for the array of locations. I suspect we need to keep the array of machine_ids for filtering, but I would imagine we can dump the array of machine_names. I would need to go back through our history... I think we had added the machine names for the app so we could more easily display the machines when pressing on the marker dot (and we're not showing machine names there anymore).

As for the location details, we are getting all the results in a single api call for a location. I'll need to study up on our options for lazy loading / how we can potentially speed that up. It may involve making updates to the api to not give us all the data at once, but I'm not sure what is necessary quite yet. Places that big are kind of their own separate concern... like... I believe employees are the ones keeping up with what machines are actually there because there are so many, average patrons can't even keep up. Disabling comments if that would help, seems like it could be a totally reasonable tradeoff... as a user of the app myself, I find comments to be especially important for places with 1-3 machines to help me decide if I want to go to that location as comments about stuff being broken matters A LOT when the number of machines is low.

**Comment by RyanTG** [comment]
I should also note that when I say the request timesout, I do not know if those are requests made via the website or via the app. The load may be different for each case. But I plan to try and look into that. The logs and stuff can be difficult to understand.

But yeah, for a start it would be interesting to see if the array of machines_names is unnecessary.
