### ISSUE TITLE
Feature Request: Make it easier to add locations (Google Places API autocomplete)

### ISSUE THREAD

**Issue by simon-o-matic** [pinballmap/pbm-react#454]
Currently you have to know the street and address to enter a new location. This is cumbersome. 

Two ideas:

1. use Google maps look ups
2. Clicking on a location on the map could offer the option to add

**Comment by RyanTG** [comment]
Thanks for the feature suggestion. We recently opened a similar issue for the website: https://github.com/pinballmap/pbm/issues/1476

I was thinking that using the google places api would work well.

**Comment by RyanTG** [comment]
Initial search: there is an npm package https://github.com/FaridSafi/react-native-google-places-autocomplete

Does not look super maintained. But still looks pretty robust.

**Comment by RyanTG** [comment]
For reference, this is implemented on the website location submission form now: https://github.com/pinballmap/pbm/commit/32890c2a9053e044be9096b63cdfc643238cd4b4

It uses the Google Places API. Didn't have to use a gem or anything. It wasn't totally straightforward because some elements, like name, website, and phone, come straight out of `places` but the components of the address (route, street, city, state, zip, etc) are bundled into `address_components` so those had to be extracted using a different method. gems/packages would make that process easier. I haven't looked into react native implementation and if the package is truly needed for our case (our use case is a simple one compared with others).
