### ISSUE TITLE
Bug: Regions undefined

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#480]
Sentry is finding two crashes that seem to be in the same category. `regions` is not found. It's not clear to me why it periodically is not found. For the AppAlert issue, I wonder if (at the least) this can be "rescued" by not attempting to show the motd if the regions data isn't found. For the Maps issue, I _think_ that logic is related to the Universal Link for a region name.

https://github.com/pinballmap/pbm-react/blob/319361c7e6cfac5414ec8a3991a58cd6d257f750/app/screens/Map.js#L110

```
TypeError
undefined is not an object (evaluating 'o.props.regions.regions.find')
```

https://github.com/pinballmap/pbm-react/blob/319361c7e6cfac5414ec8a3991a58cd6d257f750/app/components/AppAlert.js#L89

```
TypeError
undefined is not an object (evaluating 'n.regions.length')
```

**Comment by RyanTG** [comment]
My guesses, that I haven't tried:

```
const motd = regions && regions.regions.length ? regions.regions.filter(region => region.id === 1)[0].motd : ''
    return {
        motd
    }
```

and for this one, I was thinking that this one should be an `else if` and then there should be a final `else navigate('Map')`
```
} else if {
            const region = this.props.regions.regions.find(({ name }) => url.includes(name))
            if (region) {
                this.props.getLocationsByRegion(region)
            }
            navigate('Map')
        }
```
but I'm not sure how to best do that, or if that's enough. Additionally, I think `navigate('Map') should now be `navigation.navigate('MapTab')` ...?

**Comment by bpoore** [comment]
We do have the possibility of a race condition because the map screen is loading in the [regions](https://github.com/pinballmap/pbm-react/blob/master/app/screens/Map.js#L131), etc on load. I had wanted to move the fetching of these global app things to AppWrapper. We could look into doing that as part of the fix here, otherwise, yes, in these cases we need to be careful to not assume that `regions.regions` is defined. We will need to be using `regions?.regions` or `&&` in these cases- the `else if` in your most recent comment would still cause a crash here:
`const region = this.props.regions.regions.find(({ name }) => url.includes(name))`

mapStateToProps in function components is slightly old school, but there's nothing necessarily wrong with the approach. While the repo still contains class based components, I wouldn't stress about moving to more modern approaches with hooks unless we have a specific reason. Even if we were using the "newer" ways, we'd still be running into this problem where we would have assumed `regions.regions` was populated when it possibly wasn't.
