### ISSUE TITLE
Better handling or notifications for unconfirmed accounts

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm-react#519]
Logged in but unconfirmed users are in a weird state. They appear fine and logged in, but they receive “something went wrong” alerts when they try to do stuff. This is confusing, and they complain that the app is broken.

I think we need more descriptive alerts for this case! Do we have enough information to tell them they are unconfirmed?

**Comment by bpoore** [comment]
I've been looking into this- our current approach when a user makes a new account is to log them in with their new credentials, but the new credentials haven't been confirmed yet which is causing the problems the users are reporting.

Personally, I think the cleanest solution (especially as we don't currently have amazing error handling built into the app anyways) will be to update the flow on user sign up.

Proposed flow- user signs up, then we take them back to the login screen where they can login if they desire or otherwise still `Skip logging in for now`. If a user tries to log in prior to confirming their account, we already have the login screen built to not login the user, but display the following:
![simulator_screenshot_4201139F-F838-4225-B782-3E086752A250](https://github.com/pinballmap/pbm-react/assets/7720282/7d6b845d-5a04-40ff-9fa3-c92ecdeb15e5)

The change here would be not "signing in" the user on sign up, forcing the user to have confirmed their account before actually ever logging in. Does this sound like a reasonable fix? It will be more overhead to support messaging for any write/delete operation otherwise.

**Comment by RyanTG** [comment]
Yeah, this sounds great to me.

**Comment by bpoore** [comment]
Sweet. [This](https://github.com/pinballmap/pbm-react/commit/3a5ce92379d2ad7f74d990cdff5679f236f65bc8) should do it.
